---

- name: Copy logrotate.conf file
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: 0644

- name: Copy cron.hourly/logrotate file
  template:
    src: logrotate.cron.hourly.j2
    dest: /etc/cron.hourly/logrotate
    owner: root
    group: root
    mode: 0700

- name: Copy tmp configuration file
  template:
    src: "tmp.logrotate.j2"
    dest: "/etc/logrotate.d/tmp"
    owner: root
    group: root
    mode: 0644

- name: Copy syslog configuration file
  template:
    src: "syslog.logrotate.j2"
    dest: "/etc/logrotate.d/syslog"
    owner: root
    group: root
    mode: 0644
