---

- hosts: appservers, database , webservers,
  ignore_unreachable: true
  serial: 3
  roles:
    - os/packages
    - os/chrony
    - os/firewalld
    - os/host_name
    - os/logrotate

- hosts: consul-cluster
  gather_facts: false
#  serial: 1
  ignore_unreachable: true
  roles:
    - infra/consul-cluster
    - monitoring/node_exporter

- hosts: consul-agent
  gather_facts: false
  ignore_unreachable: true
  roles:
    - infra/consul-agent
    - monitoring/node_exporter
- name: Deploy PostgreSQL HA Cluster (based on "Patroni" and "{{ dcs_type }}")
  hosts: localhost
  gather_facts: false
  vars:
    minimal_ansible_version: 2.7.0
  tasks:
    - name: Checking ansible version
      fail:
        msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
      when: ansible_version.full is version(minimal_ansible_version, '<')


- hosts: postgres_cluster
  gather_facts: true
  any_errors_fatal: true


  roles:
    - role: db/add-repository
    - role: db/packages
    - role: db/sysctl
    - role: db/transparent_huge_pages
    - role: db/pam_limits
    - role: db/locales

- hosts: postgres_cluster
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: db/pg_probackup
      when: pg_probackup_install|bool

    - role: db/pgbouncer
      when: pgbouncer_install|bool

    - role: db/patroni

    # optional
    - role: db/postgresql-users
      when: is_master == "true" and postgresql_users | length > 0

    - role: db/postgresql-databases
      when: is_master == "true" and postgresql_databases | length > 0

    - role: db/postgresql-extensions
      when: is_master == "true" and postgresql_extensions | length > 0

    - role: db/pgbouncer/userlist
      when: pgbouncer_install|bool and pgbouncer_generate_userlist|bool

    - role: db/netdata
      when: netdata_install is defined and netdata_install|bool

    # finish (info)
    - role: db/deploy-finish

- hosts: appservers
  gather_facts: false
#  serial: 1
  ignore_unreachable: true
  roles:
    - monitoring/prometheus
    - monitoring/grafana

- hosts: webservers
  serial: 1
  roles:
    - apps/hosts
    - apps/django
    - apps/gunicorn

- hosts: loadbalancer
  roles:
    - apps/nginx


