---

architecture : linux_amd64
systemd_unitdir: /usr/lib/systemd/system

# Packages to install

packages:
  - epel-release
  - curl
  - gdisk
  - vim
  - net-tools
  - tcpdump
  - traceroute
  - telnet
  - wget
  - bind-utils
  - gzip
  - tar
  - unzip

# Logrotate variables

logrotate:
  owner: root
  group: root
  dir: /etc/logrotate.d

# Chrony settings

timezone: "Europe/Moscow"

ntp:
  servers:
    - pool.ntp.org
    - 1.ru.pool.ntp.org
    - 2.ru.pool.ntp.org

# Firewall Settings

firewall:
  ports:
    - 22/tcp
    - 80/tcp
    - 443/tcp
    - 8300/tcp
    - 8301/tcp
    - 8301/udp
    - 8302/tcp
    - 8302/udp
    - 8500/tcp
    - 8502/tcp
    - 8600/tcp
    - 8600/udp
    - 9100/tcp

  services:
    - http
    - https

# Consul settings

consul_server_defaults:
  service: "consul.service"

consul_agent_defaults:
  service: "consul.service"

consul:
  user: consul
  group: consul
  bin_sources: /usr/bin
  config_dir: /etc/consul.d
  data_dir: /home/consul
  service_dir: /home/consul/services
  version: 1.12.0
  key: CzmvZMSgNXMr0mJHh1Z98w==
