---

- name: Install prereq packages
  dnf:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - postgresql-libs
    - postgresql-devel
    - python3-virtualenv
    - libxml2-devel
    - libxslt-devel
    - libffi-devel
    - openssl-devel
    - redhat-rpm-config

- name: Prepare step for django
  block:
    - name: create directory for django files
      file:
        path: "{{ project.name_path }}"
        state: directory
        mode: 0755
        owner: root
        group: root

