- name: install the latest packages for firewalld
  yum:
    name: firewalld
    state: present

- name: Enable and unmask the firewalld
  systemd:
    name: "firewalld.service"
    daemon_reload: yes
    state: started
    masked: no
    enabled: yes